version: '3.8'

services:
  redis:
    image: redis:6.2
    container_name: redis6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  cms-db:
    image: mysql:8.0
    container_name: cms-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CMS_Project
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  cms-backend:
    build:
      context: ./backend
    container_name: cms-backend
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
      cms-db:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cms-db:3306/CMS_Project?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: password

volumes:
  db-data:
